name: Full Stack CI

on:
  push:
    branches: ["main", "dev"]

  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 0000
          POSTGRES_DB: userdb

        ports:
          - 5433:5432

        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://admin:0000@localhost:5433/userdb

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # =========================
      # FRONTEND
      # =========================

      - name: Install frontend dependencies
        working-directory: frontend/trainTwo
        run: npm ci

      - name: Build frontend React app
        working-directory: frontend/trainTwo
        run: npm run build

      - name: Run frontend lint
        working-directory: frontend/trainTwo
        run: npm run lint

      # =========================
      # BACKEND
      # =========================

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate

      - name: Run Prisma Migrations
        working-directory: backend
        run: npx prisma migrate deploy

      - name: Run backend tests
        working-directory: backend
        run: npm test

      - name: Build backend
        working-directory: backend
        run: npm run build

      # =========================
      # FINAL
      # =========================

      - name: Show repository files
        run: ls -R

      - name: CI Completed
        run: echo "CI Pipeline completed successfully!"
